# Generated by Django 2.1.7 on 2019-03-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maria_bs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Vocabulary',
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'verbose_name_plural': 'vocabularies'},
        ),
    ]
